### ISSUE TITLE
URL はどこですか

### ISSUE THREAD

**Issue by babcs2035** [laplaciancpp/AtCoder-ACs#1]
URL はどこですか

**Comment by lapla-cogito** [comment]
https://severrabaen.github.io/AtCoder-ACs/static/index.html
ここですが、Brythonが404エラーを吐きまくるため、正しく動作しません(F12で見てみると分かる)。よって、今後のファイルの構成が変わる可能性が十分にあるのでここが最終的なサイトURLであるとは思わないでください。あと、HTMLとCSSを気分で書いたのでデザインはまあまあ変わる予定です。
